version: "3"

services:
    user-emu:
        container_name: vivotek-user
        build:
            context: .
            dockerfile: ./user-emu/Dockerfile
        privileged: true
        ports:
            - "8888:80"
